# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT ww.wsgi

beta_settings:
    cloud_sql_instances: yuga-171020:us-central1:yuga-s1

runtime_config:
  python_version: 3
# [END runtime]