# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users_app.Story'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='approvals',
        ),
        migrations.AddField(
            model_name='story',
            name='approvals',
            field=models.ManyToManyField(related_name='user_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='story',
            name='disapprovals',
        ),
        migrations.AddField(
            model_name='story',
            name='disapprovals',
            field=models.ManyToManyField(related_name='user_disapprovals', to=settings.AUTH_USER_MODEL),
        ),
    ]
