# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-29 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20171023_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='users_app.Tag'),
        ),
        migrations.AlterField(
            model_name='story',
            name='approvals',
            field=models.ManyToManyField(blank=True, related_name='user_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='disapprovals',
            field=models.ManyToManyField(blank=True, related_name='user_disapprovals', to=settings.AUTH_USER_MODEL),
        ),
    ]
