# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20180129_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='location', to='users_app.Location'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
